### ISSUE TITLE
greetings. serious feature request

### ISSUE THREAD

**Issue by tails1974seeyounextgame** [PistolRcks/curseforge-mass-downloader#1]
hello there. is there a way to to look at each mods page or file, and convert it to the latest minecraft forge supported version, such as 12.2  >| 16.2 > /mods/{mods here}

**Comment by PistolRcks** [comment]
Yep, it is possible! But there are two caveats which make me not want to add it in.
1. Modpacks usually only support one version of Minecraft for a reason, whether that be for mod dependencies, love of a specific mod version, or love of a certain Minecraft version.
2. I don't believe it is within the scope or focus of this project.

Number 2 really is the biggest point. Could you make a script which modifies manifests to do what you want? Sure. However, the whole point of this project is to streamline the *download* (and possibly installation, which comes shortly after downloading) of mods from CurseForge, as the name says (and I even think [MultiMC](https://multimc.org/) does a better job at that). I don't think that the modification of manifest files falls within this category.

However, I *did* say it is possible. Here's how I would do it:
1. Get the latest versions of all of the mods in the modpack
2. Find the greatest version of Minecraft which all of the modpacks have (i.e. the greatest version of Minecraft supported of the mod which supports the lowest version of Minecraft)
3. Get the id of the latest version of Forge for that version (not sure if there's an API for that, you might have to do some webscraping)
4. Replace the Minecraft `version` and Forge `id` fields with those which we found

At which point you could send it through `curseforge-mass-downloader`. 

Hope that answers your question, but I'm going to have to close this for the reasons I stated earlier.
