### ISSUE TITLE
can't download mods

### ISSUE THREAD

**Issue by nicermak** [PistolRcks/curseforge-mass-downloader#4]
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by PistolRcks** [comment]
Please provide additional information (input parameters, entire log).

**Comment by PistolRcks** [comment]
Looking back at the code, it seems like your `manifest.json` is empty. Use an actual `manifest.json` file and then try again, making a new issue with proper documentation if the issue arises again.

Closing due to user error.
